### ISSUE TITLE
openpyxl missing as dependency

### ISSUE THREAD

**Issue by danielnrainer** [instamatic-dev/edtools#18]
Hiya,

Unfortunately, I'm still a novice with git and entirely unfamiliar with poetry, so I don't dare to add a pull-request (yet?)...

### Issue
When installing edtools via `pip`, the package `openpyxl` is not being installed. This leads to an error when executing `edtools.extract_xds_info` as the writing of the .xlsx file fails (see below error message).
I don't know if `pandas` is supposed to require `openpyxl` itself, so maybe it's actually only an issue in that current version, v1.4.2? I added a full list of environment packages as .txt below.

System: Win11, miniconda3 (fresh conda environment), tested in py3.8, py3.9 and py3.10

### Workaround
`pip install openpyxl`

### Suggested fix
add `openpyxl` to requirements/dependencies

Best,
Daniel

```
Traceback (most recent call last):
  File "C:\Users\danie\Miniconda3\envs\edtools\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\danie\Miniconda3\envs\edtools\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\danie\Miniconda3\envs\edtools\Scripts\edtools.extract_xds_info.exe\__main__.py", line 7, in <module>
  File "C:\Users\danie\Miniconda3\envs\edtools\lib\site-packages\edtools\extract_xds_info.py", line 437, in main
    cells_to_excel(xdsall)
  File "C:\Users\danie\Miniconda3\envs\edtools\lib\site-packages\edtools\extract_xds_info.py", line 211, in cells_to_excel
    df.to_excel(fn)
  File "C:\Users\danie\Miniconda3\envs\edtools\lib\site-packages\pandas\core\generic.py", line 2345, in to_excel
    formatter.write(
  File "C:\Users\danie\Miniconda3\envs\edtools\lib\site-packages\pandas\io\formats\excel.py", line 888, in write
    writer = ExcelWriter(  # type: ignore[abstract]
  File "C:\Users\danie\Miniconda3\envs\edtools\lib\site-packages\pandas\io\excel\_openpyxl.py", line 49, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'
```

[package_list.txt](https://github.com/instamatic-dev/edtools/files/8787803/package_list.txt)

**Comment by stefsmeets** [comment]
Thanks for the bug report! I'd also think it would be installed alongside Pandas, but apparently this is the intended behaviour: https://pandas.pydata.org/docs/getting_started/install.html#optional-dependencies 

Since we depend on this behaviour I think it should be added to our requirements. I'll fix it when I'm back in the office next week 🐱‍💻

**Comment by danielnrainer** [comment]
Thanks for picking this up straight away! :)
